#ex3_8
places = ['Cam','Jangala','Ivl','Earth']
print('Original List:\t')
print(places)
print('Sorted List:\t')
print(sorted(places))
print('Original List:\t')
print(places)
print('Sorted Reversed List:\t')
print(sorted(places, reverse=1))
print('Original List:\t')
print(places)
places.reverse()
print('Reversed Original List:\t')
print(places)
places.reverse()
print('Reversed Original List, Again:\t')
print(places)
places.sort()
print('Sorted Original List:\t')
print(places)
places.sort(reverse = 1)
print('Original List Again:\t')
print(places)
